export const SPANISH_CITIES = [
  "A Coruña",
  "Albacete",
  "Alcalá de Henares",
  "Alcobendas",
  "Alcorcón",
  "Algeciras",
  "Alicante",
  "Almería",
  "Aranjuez",
  "Ávila",
  "Avilés",
  "Badajoz",
  "Badalona",
  "Barcelona",
  "Benalmádena",
  "Bilbao",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cartagena",
  "Castellón de la Plana",
  "Ceuta",
  "Chiclana de la Frontera",
  "Ciudad Real",
  "Córdoba",
  "Cuenca",
  "Dos Hermanas",
  "Elche",
  "Estepona",
  "Ferrol",
  "Fuengirola",
  "Fuenlabrada",
  "Gandía",
  "Gijón",
  "Girona",
  "Granada",
  "Guadalajara",
  "Huelva",
  "Huesca",
  "Ibiza",
  "Jaén",
  "Jerez de la Frontera",
  "Las Palmas de Gran Canaria",
  "León",
  "Lleida",
  "Logroño",
  "Lugo",
  "Madrid",
  "Majadahonda",
  "Marbella",
  "Mataró",
  "Melilla",
  "Mérida",
  "Móstoles",
  "Murcia",
  "Ourense",
  "Oviedo",
  "Palencia",
  "Palma",
  "Pamplona",
  "Pontevedra",
  "Pozuelo de Alarcón",
  "Reus",
  "Sabadell",
  "Salamanca",
  "San Cristóbal de La Laguna",
  "San Sebastián",
  "Sant Cugat del Vallès",
  "Santander",
  "Santiago de Compostela",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Terrassa",
  "Toledo",
  "Torrejón de Ardoz",
  "Torremolinos",
  "Valdemoro",
  "Valencia",
  "Valladolid",
  "Vigo",
  "Vitoria-Gasteiz",
  "Zamora",
  "Zaragoza",
] as const;
